In [23]:
import math as m
import numpy as np

In [24]:
a = (2, 1)

print(sum(a))

3


In [25]:
a = [[0, 0], [0, 0]]
b = (1, 2, 3)
a[0][0] = b
print(a)

[[(1, 2, 3), 0], [0, 0]]


In [26]:
a = 1 + 2j
print(a.real)

1.0


In [27]:
a = 1.6
print(type(m.floor(a)))

<class 'int'>


In [35]:
a = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[7, 8, 9], [10, 11, 12]]]
a = np.array(a)
print((a.shape[1]))

# b = np.zeros((2, 2, 3))

# print(b[0, 0])

2


In [29]:
a = (0, 1, 2)
b = [*a]
print(b)

[0, 1, 2]


In [30]:
M = [
  [(0, 0, 255), (0, 255, 0)],
  [(255, 0, 0), (0, 0, 0)]
]

print(np.array(M))

[[[  0   0 255]
  [  0 255   0]]

 [[255   0   0]
  [  0   0   0]]]


In [41]:
a = 1+8j
b = 2+9j

c = np.array([a, b])
print(c)

[1.+8.j 2.+9.j]


In [45]:
print(np.complex64((2, 2)))

[2.+0.j 2.+0.j]
